### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by volkb** [NASA-IMPACT/data_share#2]
To download the image data, I am directed to use GIBS through an API call; however, the script given to generate the variables for that call does not work and is not commented such that I can alter it to work. Please include a fully working variable/url generation script compatible for python 3.x.

Also, documentation lists `You can download the files from: s3://hls-datashare.`. the url provided is a shared network drive that seems to only be accessible from an internal network. please provide an external link or alternative repository.

**Comment by xhagrg** [comment]
@volkb Just updated the README. Let us know if you find any issues in accessing the data or using the code snippet. Re-iterating on the data access issue: you'll have to use `awscli` to access the data.
